spring:
  application:
    name: todolist
  datasource:
    url: jdbc:mariadb://localhost:3308/myprojectdb
    username: myproject
    password: myproject1!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true